tips:
  search-api-index-fields-label:
    label: Nimetus
  search-api-index-fields-machine-name:
    label: 'Süsteemne nimetus'
  search-api-index-fields-type:
    label: Type
  search-api-index-fields-boost:
    label: Kiirendamine
  search-api-index-fields-edit:
    label: 'Muuda välja'
  search-api-index-fields-remove:
    label: 'Eemalda väli'
  search-api-index-fields-submit:
    label: 'Salvesta muudatused'
