tips:
  search-api-index-fields-add:
    label: 'Mezők hozzáadása'
  search-api-index-fields-label:
    label: Címke
  search-api-index-fields-machine-name:
    label: 'Programok által használt név'
  search-api-index-fields-type:
    label: Type
  search-api-index-fields-boost:
    label: Kiemelés
  search-api-index-fields-edit:
    label: 'Mező szerkesztése'
  search-api-index-fields-remove:
    label: 'Mező törlése'
  search-api-index-fields-submit:
    label: 'Változások mentése'
  search-api-index-fields-cancel:
    label: 'Változtatások visszavonása'
